In [2]:
# Using pandas to load chracters

import pandas as pd
df = pd.read_csv("./star_wars/csv/characters.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           112 non-null    int64
 1   name         112 non-null    object
 2   species      112 non-null    object
 3   gender       108 non-null    object
 4   height       83 non-null     float64
 5   weight       77 non-null     float64
 6   hair_color   76 non-null     object
 7   eye_color    104 non-null    object
 8   skin_color   110 non-null    object
 9   year_born    80 non-null     object
 10  homeworld    99 non-null     object
 11  year_died    50 non-null     object
 12  description  112 non-null    object
dtypes: float64(2), int64(1), object(10)
memory usage: 11.5+ KB

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
0,1,Luke Skywalker,Human,Male,1.72,77.0,Blond,Blue,Light,19,Tatooine,34,The main protagonist of the original trilogy.
1,2,Leia Organa,Human,Female,1.50,49.0,Brown,Brown,Light,19,Alderaan,35,A leader in the Rebel Alliance and twin sister...
2,3,Darth Vader,Human,Male,2.02,136.0,NaN,Yellow,Pale,41,Tatooine,4,The Sith Lord formerly known as Anakin Skywalker.
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896,Unknown,4,A wise and powerful Jedi Master.
4,5,Han Solo,Human,Male,1.80,80.0,Brown,Hazel,Light,29,Corellia,34,A smuggler turned hero in the Rebel Alliance.

In [ ]:
# Find all rows where species is Human

df2 = df.loc[(df['species'] == "Human")]
df2.head()

1. Is Human
1. Is Not Human

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896,Unknown,4,A wise and powerful Jedi Master.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52,Naboo,NaN,A clumsy Gungan who became a representative in...
18,19,BB-8,Droid,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,A spherical astromech droid.
19,20,C-3PO,Droid,NaN,1.71,NaN,NaN,NaN,Gold,112,Tatooine,NaN,A protocol droid fluent in over six million fo...

In [6]:
# Find all rows where species is Not Human
df3 = df.loc[(df['species'] != "Human")]
df3.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896,Unknown,4,A wise and powerful Jedi Master.
5,6,Chewbacca,Wookiee,Male,2.28,112.0,Brown,Blue,Brown,200,Kashyyyk,NaN,A loyal Wookiee and co-pilot of the Millennium...
12,13,Jar Jar Binks,Gungan,Male,1.96,66.0,NaN,Orange,Orange,52,Naboo,NaN,A clumsy Gungan who became a representative in...
18,19,BB-8,Droid,NaN,NaN,NaN,NaN,NaN,White,NaN,NaN,NaN,A spherical astromech droid.
19,20,C-3PO,Droid,NaN,1.71,NaN,NaN,NaN,Gold,112,Tatooine,NaN,A protocol droid fluent in over six million fo...

In [9]:
# Find all rows where species is Not Human and Height < 1.5
df4 = df[(df['species'] != "Human") & (df['height'] < 1.5)]
df4.head()

,id,name,species,gender,height,weight,hair_color,eye_color,skin_color,year_born,homeworld,year_died,description
3,4,Yoda,Yoda's species,Male,0.66,17.0,White,Brown,Green,896,Unknown,4,A wise and powerful Jedi Master.
20,21,R2-D2,Droid,NaN,0.96,NaN,NaN,NaN,White/Blue,33,Naboo,NaN,An astromech droid known for his bravery and r...
27,28,Maz Kanata,Unknown,Female,1.24,31.0,NaN,Brown,Orange,973,Takodana,NaN,A wise and ancient being who runs a tavern on ...
49,50,Sebulba,Dug,Male,1.12,40.0,NaN,Red,Brown,32,Malastare,NaN,A pod racer with a fierce reputation.
53,54,Wicket W. Warrick,Ewok,Male,1.00,20.0,Brown,Brown,Brown,23,Endor,NaN,An Ewok who helped the Rebel Alliance on Endor.