# Exercise 3 - stack the country statistics

A) Use pandas.concat to combine 4 countries from the Maddisson CSV files in one df.

```python
import pandas as pd

afghanistan_df = pd.read_csv("./countries/Afghanistan.csv")
albania_df = pd.read_csv("./countries/Albania.csv")
algeria_df = pd.read_csv("./countries/Algeria.csv")
angola_df = pd.read_csv("./countries/Angola.csv")

df = pd.concat([afghanistan_df, albania_df, algeria_df, angola_df], ignore_index=True)
df.head()
```

B) In Task 1, you used pandas to find statistical data for one country. Now, do the same for four different countries and use `pandas.concat()` to combine the results into a single DataFrame.

```python
# Lamda function for each data group (by Entity, DataFrameGroupBy)
def analyze_entity(dg):
    min_year = dg["Year"].min()
    max_year = dg["Year"].max()
    min_gdp = dg.loc[dg["Year"].idxmin(), "GDP"] / 10**9
    max_gdp = dg.loc[dg["Year"].idxmax(), "GDP"] / 10**9
    avg = dg["GDP"].mean() / 10**9
    n = max_year - min_year
    cagr = round(((max_gdp / min_gdp) ** (1 / n) - 1) * 100, 2)
    # Create a new row with data
    return pd.Series({
        "Min Year": min_year,
        "Max Year": max_year,
        "Min GDP (B$)": round(min_gdp, 2),
        "Max GDP (B$)": round(max_gdp, 2),
        "Avg GDP (B$)": round(avg, 2),
        "CAGR %": cagr,
    })

# DataFrameGroupBy is a pandas class — the object returned by df.groupby(...).
print(type(df.groupby("Entity"))) # --> DataFrameGroupBy
# For each group, call analyze_entity to calculate the create new series (row) data for them
results = df.groupby("Entity")[["Year", "GDP"]].apply(analyze_entity).reset_index()
results
```

# Output
```
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

Entity	        Min Year	Max Year	Min GDP (B$)	Max GDP (B$)	Avg GDP (B$)	CAGR %
0	Afghanistan	1950.0	    2022.0	    9.42	        53.30	        23.70	        2.44
1	Albania	    1870.0	    2022.0	    0.43	        36.17	        12.55	        2.96
2	Algeria	    1820.0	    2022.0	    1.84	        595.82	        184.65	        2.90
3	Angola	    1950.0	    2022.0	    6.91	        158.35	        43.77	        4.45
```

In [3]:
import pandas as pd

afghanistan_df = pd.read_csv("./countries/Afghanistan.csv")
albania_df = pd.read_csv("./countries/Albania.csv")
algeria_df = pd.read_csv("./countries/Algeria.csv")
angola_df = pd.read_csv("./countries/Angola.csv")

df = pd.concat([afghanistan_df, albania_df, algeria_df, angola_df], ignore_index=True)
df.head()

        Entity Code  Year          GDP  GDP (Annotations)
0  Afghanistan  AFG  1950   9421400000                NaN
1  Afghanistan  AFG  1951   9692280000                NaN
2  Afghanistan  AFG  1952  10017325000                NaN
3  Afghanistan  AFG  1953  10630520000                NaN
4  Afghanistan  AFG  1954  10866360000                NaN

In [4]:
# Lamda function for each data group (by Entity, DataFrameGroupBy)
def analyze_entity(dg):
    min_year = dg["Year"].min()
    max_year = dg["Year"].max()
    min_gdp = dg.loc[dg["Year"].idxmin(), "GDP"] / 10**9
    max_gdp = dg.loc[dg["Year"].idxmax(), "GDP"] / 10**9
    avg = dg["GDP"].mean() / 10**9
    n = max_year - min_year
    cagr = round(((max_gdp / min_gdp) ** (1 / n) - 1) * 100, 2)
    # Create a new row with data
    return pd.Series({
        "Min Year": min_year,
        "Max Year": max_year,
        "Min GDP (B$)": round(min_gdp, 2),
        "Max GDP (B$)": round(max_gdp, 2),
        "Avg GDP (B$)": round(avg, 2),
        "CAGR %": cagr,
    })

# DataFrameGroupBy is a pandas class — the object returned by df.groupby(...).
print(type(df.groupby("Entity"))) # --> DataFrameGroupBy
# For each group, call analyze_entity to calculate the create new series (row) data for them
results = df.groupby("Entity")[["Year", "GDP"]].apply(analyze_entity).reset_index()
results

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

,Entity,Min Year,Max Year,Min GDP (B$),Max GDP (B$),Avg GDP (B$),CAGR %
0,Afghanistan,1950.0,2022.0,9.42,53.30,23.70,2.44
1,Albania,1870.0,2022.0,0.43,36.17,12.55,2.96
2,Algeria,1820.0,2022.0,1.84,595.82,184.65,2.90
3,Angola,1950.0,2022.0,6.91,158.35,43.77,4.45